{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "2f513bd9-e01d-4501-99d8-03bea91e75d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                             headline  \\\n",
      "26  Sources expect active NFL trade market ahead o...   \n",
      "19  Broncos' Sean Payton on playing football in En...   \n",
      "1   NFL Week 6 uniforms: Falcons, Bills' MNF throw...   \n",
      "2   Falcons rule WR Darnell Mooney (hamstring) out...   \n",
      "0   Jets-Broncos: Sights and sounds from the NFL's...   \n",
      "13  Bills place Hamlin, Sanders on IR, rule Milano...   \n",
      "3           Fantasy football rankings for Week 6: IDP   \n",
      "6          Fantasy football rankings for Week 6: D/ST   \n",
      "5        Fantasy football rankings for Week 6: Kicker   \n",
      "4     Fantasy football rankings for Week 6: Tight end   \n",
      "7   Fantasy football rankings for Week 6: Wide rec...   \n",
      "8   Fantasy football rankings for Week 6: Running ...   \n",
      "9   Fantasy football rankings for Week 6: Quarterback   \n",
      "10           Fantasy football PPR rankings for Week 6   \n",
      "12  Bears to start LT Theo Benedet over Braxton Jo...   \n",
      "11  Fantasy football flex and superflex rankings f...   \n",
      "14  Commanders rule out receivers McLaurin, Brown ...   \n",
      "47  Fantasy playbook: NFL Week 6 Shadow Reports, l...   \n",
      "31  Cowboys RB Miles Sanders to have season-ending...   \n",
      "30  Short-handed Seahawks likely down 3 starting D...   \n",
      "28  Niners' Jones to start again in Purdy's place;...   \n",
      "15  Fantasy Football Buzz: What impact will foot i...   \n",
      "35  Steelers' Porter, Highsmith, Ramsey taken off ...   \n",
      "16  Pat McAfee and Dan Lanning rip off their shirt...   \n",
      "17  Chargers look to lean on 'focus training' to c...   \n",
      "23  A look at the historic last-minute heroics in ...   \n",
      "32  Raiders tight end Brock Bowers to miss second ...   \n",
      "20   Should the Jets be movers at the trade deadline?   \n",
      "18  NFL Week 6 predictions, fantasy sleepers, upse...   \n",
      "25  Dolphins rookie linemen Kenneth Grant, Jonah S...   \n",
      "22  How Deebo Samuel became an instant hit in Wash...   \n",
      "21  Cowboys OC Klayton Adams has helped Javonte Wi...   \n",
      "24  How Elijah Wilkinson stabilized Falcons' OL af...   \n",
      "43  Bills vs Falcons, Bears vs Commanders: How to ...   \n",
      "27        Bo Nix and wife Izzy Nix announce pregnancy   \n",
      "29  Patriots OT Morgan Moses on game captain selec...   \n",
      "33  Ravens rule out QB Lamar Jackson for second st...   \n",
      "34  Why you should consider adding Isaiah Bond in ...   \n",
      "36  Colts' Jonathon Taylor leads Week 5 Madden NFL...   \n",
      "37  Brian Burns loves 'fearless' Jaxson Dart-Cam S...   \n",
      "42  Browns' Shedeur Sanders to back up Dillon Gabr...   \n",
      "38  Greg Newsome on being traded to Jaguars: 'It f...   \n",
      "39    How Joe Flacco is approaching his Bengals debut   \n",
      "41  Source: Cowboys' Jerry Jones won't appeal $250...   \n",
      "44  Schefter expects major activity during NFL tra...   \n",
      "40             Can Joe Flacco beat the Packers again?   \n",
      "45  Schefter to McAfee: NFL reviewing Giants' conc...   \n",
      "46  Panthers RB Hubbard out, Dowdle gets shot vs. ...   \n",
      "48  Why Daniel Dopp is starting Tucker Kraft with ...   \n",
      "49     Should you start Kenneth Walker III in Week 6?   \n",
      "\n",
      "                                          description  \\\n",
      "26  Sources expect more trade activity ahead of th...   \n",
      "19  Before he became a Super Bowl-winning coach, P...   \n",
      "1   Two throwback threads return in Week 6 of the ...   \n",
      "2   Falcons No. 2 wide receiver Darnell Mooney has...   \n",
      "0   The NFL played its second consecutive game in ...   \n",
      "13  The Bills placed S Damar Hamlin and DT T.J. Sa...   \n",
      "3   Weekly fantasy football draft rankings for IDP...   \n",
      "6   Fantasy football rankings from Matt Bowen, Mik...   \n",
      "5   Fantasy football rankings from Matt Bowen, Mik...   \n",
      "4   Fantasy football rankings from Matt Bowen, Mik...   \n",
      "7   Fantasy football rankings from Matt Bowen, Mik...   \n",
      "8   Fantasy football rankings from Matt Bowen, Mik...   \n",
      "9   Fantasy football rankings from Matt Bowen, Mik...   \n",
      "10  Weekly individual and composite rankings for e...   \n",
      "12  The Bears will debut a new left tackle Sunday ...   \n",
      "11  Trying to decide between a couple of closely r...   \n",
      "14  Commanders coach Dan Quinn has ruled out wide ...   \n",
      "47  An all-encompassing look at the matchups to ex...   \n",
      "31  Cowboys running back Miles Sanders needs seaso...   \n",
      "30  The Seattle secondary hasn't been whole since ...   \n",
      "28  Mac Jones is slated to start in place of the i...   \n",
      "15  Kyler Murray was able to play through a foot i...   \n",
      "35  Steelers cornerbacks Joey Porter Jr. and Jalen...   \n",
      "16  Nick Saban hypes up Pat McAfee and Oregon coac...   \n",
      "17  Inside what \"focus training\" is and how the Ch...   \n",
      "23  The 17 games that featured a go-ahead score in...   \n",
      "32  Raiders tight end Brock Bowers (knee) will mis...   \n",
      "20  After an 0-5 start, New York might be thinking...   \n",
      "18  Could Sam Darnold be a fantasy sleeper? Can th...   \n",
      "25  Kenneth Grant and Jonah Savaiinaea have yet to...   \n",
      "22  Samuel has made an instant impact in Washingto...   \n",
      "21  Adams works in conjunction with head coach Bri...   \n",
      "24  When Kaleb McGary was lost due to injury, Elij...   \n",
      "43  Week 6 \"Monday Night Football\" doubleheader co...   \n",
      "27  The Denver Broncos quarterback announced the n...   \n",
      "29  Veteran OT Morgan Moses explains how the Patri...   \n",
      "33  The Ravens have ruled quarterback Lamar Jackso...   \n",
      "34  Matt Bowen breaks down why he likes the trajec...   \n",
      "36  NFL players made major jumps with some losses ...   \n",
      "37  Brian Burns joins “The Rich Eisen Show” to dis...   \n",
      "42  Shedeur Sanders will be the backup quarterback...   \n",
      "38  Cornerback Greg Newsome said that 'it feels am...   \n",
      "39  Joe Flacco speaks to the media for the first t...   \n",
      "41  Cowboys owner Jerry Jones won't appeal the $25...   \n",
      "44  Adam Schefter joins \"The Pat McAfee Show\" to d...   \n",
      "40  Kirk Herbstreit joins \"The Pat McAfee Show\" to...   \n",
      "45  Adam Schefter discusses with Pat McAfee how th...   \n",
      "46  Panthers running back Rico Dowdle will have an...   \n",
      "48  Daniel Dopp explains why fantasy managers shou...   \n",
      "49  Daniel Dopp explains why Kenneth Walker III is...   \n",
      "\n",
      "                   published  \\\n",
      "26 2025-10-12 01:06:54+00:00   \n",
      "19 2025-10-12 00:52:20+00:00   \n",
      "1  2025-10-12 00:15:14+00:00   \n",
      "2  2025-10-11 19:41:24+00:00   \n",
      "0  2025-10-11 19:36:27+00:00   \n",
      "13 2025-10-11 18:55:49+00:00   \n",
      "3  2025-10-11 18:17:12+00:00   \n",
      "6  2025-10-11 18:16:55+00:00   \n",
      "5  2025-10-11 18:16:38+00:00   \n",
      "4  2025-10-11 18:16:22+00:00   \n",
      "7  2025-10-11 18:15:58+00:00   \n",
      "8  2025-10-11 18:15:37+00:00   \n",
      "9  2025-10-11 18:15:18+00:00   \n",
      "10 2025-10-11 18:14:56+00:00   \n",
      "12 2025-10-11 18:12:45+00:00   \n",
      "11 2025-10-11 18:12:43+00:00   \n",
      "14 2025-10-11 17:40:59+00:00   \n",
      "47 2025-10-11 16:29:15+00:00   \n",
      "31 2025-10-11 16:20:43+00:00   \n",
      "30 2025-10-11 16:16:40+00:00   \n",
      "28 2025-10-11 16:07:38+00:00   \n",
      "15 2025-10-11 16:03:45+00:00   \n",
      "35 2025-10-11 15:43:56+00:00   \n",
      "16 2025-10-11 15:42:03+00:00   \n",
      "17 2025-10-11 14:42:23+00:00   \n",
      "23 2025-10-11 11:53:40+00:00   \n",
      "32 2025-10-11 11:13:58+00:00   \n",
      "20 2025-10-11 10:56:47+00:00   \n",
      "18 2025-10-11 10:28:16+00:00   \n",
      "25 2025-10-11 10:00:21+00:00   \n",
      "22 2025-10-11 10:00:21+00:00   \n",
      "21 2025-10-11 10:00:02+00:00   \n",
      "24 2025-10-11 10:00:02+00:00   \n",
      "43 2025-10-11 01:51:14+00:00   \n",
      "27 2025-10-11 00:39:42+00:00   \n",
      "29 2025-10-10 22:39:31+00:00   \n",
      "33 2025-10-10 21:26:07+00:00   \n",
      "34 2025-10-10 20:25:30+00:00   \n",
      "36 2025-10-10 19:49:53+00:00   \n",
      "37 2025-10-10 19:47:18+00:00   \n",
      "42 2025-10-10 19:18:21+00:00   \n",
      "38 2025-10-10 19:08:39+00:00   \n",
      "39 2025-10-10 19:06:46+00:00   \n",
      "41 2025-10-10 18:49:41+00:00   \n",
      "44 2025-10-10 18:49:17+00:00   \n",
      "40 2025-10-10 18:39:43+00:00   \n",
      "45 2025-10-10 18:37:38+00:00   \n",
      "46 2025-10-10 18:11:45+00:00   \n",
      "48 2025-10-10 16:34:50+00:00   \n",
      "49 2025-10-10 16:33:47+00:00   \n",
      "\n",
      "                                                 link  \\\n",
      "26  https://www.espn.com/nfl/story/_/id/46556471/s...   \n",
      "19  https://www.espn.com/nfl/story/_/id/46545070/b...   \n",
      "1   https://www.espn.com/nfl/story/_/id/46514452/n...   \n",
      "2   https://www.espn.com/nfl/story/_/id/46563038/f...   \n",
      "0   https://www.espn.com/nfl/story/_/id/46530078/n...   \n",
      "13  https://www.espn.com/nfl/story/_/id/46562241/b...   \n",
      "3   https://www.espn.com/fantasy/football/story/_/...   \n",
      "6   https://www.espn.com/fantasy/football/story/_/...   \n",
      "5   https://www.espn.com/fantasy/football/story/_/...   \n",
      "4   https://www.espn.com/fantasy/football/story/_/...   \n",
      "7   https://www.espn.com/fantasy/football/story/_/...   \n",
      "8   https://www.espn.com/fantasy/football/story/_/...   \n",
      "9   https://www.espn.com/fantasy/football/story/_/...   \n",
      "10  https://www.espn.com/fantasy/football/story/_/...   \n",
      "12  https://www.espn.com/college-football/story/_/...   \n",
      "11  https://www.espn.com/fantasy/football/story/_/...   \n",
      "14  https://www.espn.com/nfl/story/_/id/46562230/c...   \n",
      "47  https://www.espn.com/fantasy/football/story/_/...   \n",
      "31  https://www.espn.com/nfl/story/_/id/46554845/c...   \n",
      "30  https://www.espn.com/nfl/story/_/id/46555152/s...   \n",
      "28  https://www.espn.com/nfl/story/_/id/46555406/n...   \n",
      "15  https://www.espn.com/fantasy/football/story/_/...   \n",
      "35  https://www.espn.com/nfl/story/_/id/46554330/s...   \n",
      "16        https://www.espn.com/video/clip?id=46561392   \n",
      "17  https://www.espn.com/nfl/story/_/id/46557055/2...   \n",
      "23  https://www.espn.com/nfl/story/_/id/46554443/h...   \n",
      "32  https://www.espn.com/nfl/story/_/id/46554737/r...   \n",
      "20  https://www.espn.com/nfl/story/_/id/46546834/n...   \n",
      "18  https://www.espn.com/nfl/story/_/id/46521299/2...   \n",
      "25  https://www.espn.com/nfl/story/_/id/46556501/d...   \n",
      "22  https://www.espn.com/nfl/story/_/id/46555927/d...   \n",
      "21  https://www.espn.com/nfl/story/_/id/46544639/n...   \n",
      "24  https://www.espn.com/nfl/story/_/id/46554914/n...   \n",
      "43  https://www.espn.com/nfl/story/_/id/46543339/w...   \n",
      "27  https://www.espn.com/nfl/story/_/id/46555700/b...   \n",
      "29        https://www.espn.com/video/clip?id=46555291   \n",
      "33  https://www.espn.com/nfl/story/_/id/46554698/r...   \n",
      "34        https://www.espn.com/video/clip?id=46554430   \n",
      "36  https://www.espn.com/gaming/story/_/id/4655366...   \n",
      "37        https://www.espn.com/video/clip?id=46554229   \n",
      "42  https://www.espn.com/nfl/story/_/id/46553513/b...   \n",
      "38  https://www.espn.com/nfl/story/_/id/46553928/f...   \n",
      "39        https://www.espn.com/video/clip?id=46553774   \n",
      "41  https://www.espn.com/nfl/story/_/id/46553516/c...   \n",
      "44        https://www.espn.com/video/clip?id=46553441   \n",
      "40        https://www.espn.com/video/clip?id=46553553   \n",
      "45        https://www.espn.com/video/clip?id=46553422   \n",
      "46  https://www.espn.com/nfl/story/_/id/46553414/p...   \n",
      "48        https://www.espn.com/video/clip?id=46553133   \n",
      "49        https://www.espn.com/video/clip?id=46553134   \n",
      "\n",
      "                                 team  \n",
      "26                            Generic  \n",
      "19                            Broncos  \n",
      "1                      Bills, Falcons  \n",
      "2                      Bills, Falcons  \n",
      "0                       Broncos, Jets  \n",
      "13                     Bills, Falcons  \n",
      "3                             Generic  \n",
      "6                             Generic  \n",
      "5                             Generic  \n",
      "4                             Generic  \n",
      "7                             Generic  \n",
      "8                             Generic  \n",
      "9                             Generic  \n",
      "10                            Generic  \n",
      "12                  Bears, Commanders  \n",
      "11                            Generic  \n",
      "14                  Bears, Commanders  \n",
      "47                            Generic  \n",
      "31                            Cowboys  \n",
      "30                  Jaguars, Seahawks  \n",
      "28                         Buccaneers  \n",
      "15                            Generic  \n",
      "35             Browns, Rams, Steelers  \n",
      "16                            Generic  \n",
      "17                           Chargers  \n",
      "23                            Generic  \n",
      "32                    Raiders, Titans  \n",
      "20                               Jets  \n",
      "18                      Chiefs, Lions  \n",
      "25                           Dolphins  \n",
      "22                            Generic  \n",
      "21                            Cowboys  \n",
      "24                            Falcons  \n",
      "43  Bears, Bills, Commanders, Falcons  \n",
      "27                            Broncos  \n",
      "29                           Patriots  \n",
      "33                       Rams, Ravens  \n",
      "34                            Generic  \n",
      "36                              Colts  \n",
      "37                     Eagles, Giants  \n",
      "42                   Browns, Steelers  \n",
      "38                    Browns, Jaguars  \n",
      "39                   Bengals, Packers  \n",
      "41                      Cowboys, Jets  \n",
      "44                            Generic  \n",
      "40                   Bengals, Packers  \n",
      "45                             Giants  \n",
      "46                  Cowboys, Panthers  \n",
      "48                            Bengals  \n",
      "49                  Jaguars, Seahawks  \n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "nfl_teams = ['Bears', 'Bengals', 'Bills', 'Broncos', 'Browns', 'Buccaneers', 'Cardinals', 'Chargers', 'Chiefs', 'Colts', 'Commanders', 'Cowboys', 'Dolphins', 'Eagles', 'Falcons', 'Giants', 'Jaguars', 'Jets', 'Lions', 'Packers', 'Panthers', 'Patriots', 'Raiders', 'Rams', 'Ravens', 'Saints', 'Seahawks', 'Steelers', 'Texans', 'Titans', 'Vikings', '49ers']\n",
    "\n",
    "def fetch_nfl_news(limit=50):\n",
    "    url = f\"https://site.api.espn.com/apis/site/v2/sports/football/nfl/news?limit={limit}\"\n",
    "    response = requests.get(url)\n",
    "    if response.status_code == 200:\n",
    "        data = response.json()\n",
    "        articles = data.get('articles', [])\n",
    "        news_data = []\n",
    "        for article in articles:\n",
    "            headline = article.get('headline', '')\n",
    "            description = article.get('description', '')\n",
    "            text = headline + ' ' + description\n",
    "            relevant_teams = [team for team in nfl_teams if team in text]\n",
    "            news_data.append({\n",
    "                'headline': headline,\n",
    "                'description': description,\n",
    "                'published': article.get('published'),\n",
    "                'link': article.get('links', {}).get('web', {}).get('href'),\n",
    "                'team': ', '.join(relevant_teams) if relevant_teams else 'Generic'\n",
    "            })\n",
    "        df = pd.DataFrame(news_data)\n",
    "        df['published'] = pd.to_datetime(df['published'])\n",
    "        df = df.sort_values(by='published', ascending=False)\n",
    "        return df\n",
    "    return pd.DataFrame()\n",
    "\n",
    "news_df = fetch_nfl_news()\n",
    "print(news_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "10eaec0d-7e8e-4c6e-bf9b-684db5058899",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
