[theme]
base = "dark"
primaryColor = "#0066CC"  # NFL Blue
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
font = "sans serif"

[browser]
gatherUsageStats = false
